version: 0.2

phases:
  install:
    commands:
      # install terraform binary
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
    finally:
      - terraform --version
  pre_build:
    commands:
      - terraform validate
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - terraform apply -auto-approve
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...